# Generated by Django 4.1.7 on 2023-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("Programmers", models.ManyToManyField(to="modelapp.programmer")),
            ],
        ),
    ]
